language: c
dist: xenial
sudo: required

branches:
  only:
  - master

env:
  matrix:
    - OPENSSL="OpenSSL_1_0_2-stable"
    - OPENSSL="OpenSSL_1_1_0-stable"

compiler:
  - gcc
  - clang

os:
  - linux

matrix:
  include:
    - os: linux
      compiler: gcc

install:
  - ./.travis.sh

script:
  - build=$(dpkg-architecture -qDEB_HOST_GNU_TYPE)
  - host="${CI_JOB_NAME#*.cross.}"
  - git clone git://git.libssh.org/projects/libssh.git -b master --depth=1
  - cd libssh
  - mkdir -p obj && cd obj && cmake
    -DCMAKE_C_COMPILER="${CC}"
    -DCMAKE_BUILD_TYPE=RelWithDebInfo
    -DUNIT_TESTING=ON -DWITH_SFTP=ON -DWITH_SERVER=ON -DWITH_ZLIB=ON
    -DWITH_PCAP=ON .. &&
    make -j$(nproc) &&
    ctest --output-on-failure

