version: 0.1.0.{build}

image: Visual Studio 2017

platform:
  - x86
  - x64

configuration:
  - Release
  - Debug

install:
  - ps: >-
      If ($env:Platform -Match "x86") {
        $env:VCPKG_DEFAULT_TRIPLET="x86-windows"
        $env:CMAKE_ARCH_FLAG=""
      } Else {
        $env:VCPKG_DEFAULT_TRIPLET="x64-windows"
        $env:CMAKE_ARCH_FLAG="-A x64"
      }
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  # Install dependencies
  - vcpkg install zlib
  - vcpkg install openssl
  # Using local vcpkg port of cmocka
  - xcopy %APPVEYOR_BUILD_FOLDER%\vcpkg\cmocka ports\cmocka /E /I
  - vcpkg install cmocka
  - vcpkg integrate install
  - cd %APPVEYOR_BUILD_FOLDER%

build_script:
  - git clone git://git.libssh.org/projects/libssh.git -b master --depth=1
  - cd libssh\obj
  - cmake %CMAKE_ARCH_FLAG%
    -DCMAKE_TOOLCHAIN_FILE="c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake"
    -DUNIT_TESTING=ON -DWITH_SFTP=ON -DWITH_SERVER=ON -DWITH_ZLIB=ON
    -DWITH_PCAP=ON ..
  - dir
  - cmake --build .
  - ctest --output-on-failure

cache:
  - C:\tools\vcpkg\installed\
