version: 0.1.0.{build}

image: Visual Studio 2017

platform:
  - x86
  - x64

configuration:
  - Release
  - Debug

install:
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  # Install vcpackages for dependencies
  - vcpkg install zlib:%PLATFORM%-windows
  - vcpkg install openssl:%PLATFORM%-windows
  # Using local vcpkg port of cmocka
  - xcopy %APPVEYOR_BUILD_FOLDER%\vcpkg\cmocka ports\cmocka /E /I
  - vcpkg install cmocka:%PLATFORM%-windows
  - cd %APPVEYOR_BUILD_FOLDER%

build_script:
  - ps: >-
      If ($env:Platform -Match "x86") {
        #$env:VCVARS_PLATFORM="x86"
        #$env:ENV_PLATFORM="x86"
        "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
      } Else {
        #$env:VCVARS_PLATFORM="amd64"
        #$env:ENV_PLATFORM="x64"
        "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
      }
  - git clone git://git.libssh.org/projects/libssh.git -b master --depth=1
  - cd libssh\obj
  - cmake
    -DUNIT_TESTING=ON -DWITH_SFTP=ON -DWITH_SERVER=ON -DWITH_ZLIB=ON
    -DWITH_PCAP=ON ..
  #  -DCMAKE_TOOLCHAIN_FILE="c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake"
  - dir
#  - msbuild libssh.sln /p:Configuration="%CONFIGURATION%" /p:Platform="%PLATFORM%"
  - msbuild libssh.sln
  - ctest --output-on-failure

cache:
  - C:\tools\vcpkg\installed\
