version: 0.1.0.{build}

image: Visual Studio 2017

platform:
  - x86
  - x64

configuration:
  - Release
  - Debug

install:
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  # Install vcpackages for dependencies
  - vcpkg install zlib:%PLATFORM%-windows
  - vcpkg install openssl:%PLATFORM%-windows
  - cd %APPVEYOR_BUILD_FOLDER%
  # Temporarily installing cmocka from source
  - git clone git://git.cryptomilk.org/projects/cmocka.git -b cmocka-1.1.3 --depth=1
  - cd cmocka
  - mkdir build
  - cd build
  - cmake
    -G "Visual Studio 15 2017"
    -A "%PLATFORM%"
    -DCMAKE_BUILD_TYPE=%CONFIGURATION%
    -DCMAKE_INSTALL_PREFIX="c:/vcpkg/installed"
    ..
  # -DCMAKE_TOOLCHAIN_FILE="c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake"
  - dir
  - echo running msbuild cmocka.sln /p:Configuration="%CONFIGURATION%" /p:Platform="%PLATFORM%""
  - msbuild cmocka.sln /p:Configuration="%CONFIGURATION%" /p:Platform="%PLATFORM%"
  - cd %APPVEYOR_BUILD_FOLDER%

build_script:
  - git clone git://git.libssh.org/projects/libssh.git -b master --depth=1
  - cd libssh\obj
  - cmake
    -DCMAKE_TOOLCHAIN_FILE="c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake"
    -DUNIT_TESTING=ON -DWITH_SFTP=ON -DWITH_SERVER=ON -DWITH_ZLIB=ON
    -DWITH_PCAP=ON ..
  - dir
  - msbuild libssh.sln /p:Configuration="%CONFIGURATION%" /p:Platform="%PLATFORM%"
  - ctest --output-on-failure

cache:
  - C:\tools\vcpkg\installed\
